"""empty message

Revision ID: 3321a675fd93
Revises: 36b93d81ad60
Create Date: 2015-02-27 10:32:46.583282

"""

# revision identifiers, used by Alembic.
revision = '3321a675fd93'
down_revision = '36b93d81ad60'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loguser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('David', sa.String(), nullable=False),
    sa.Column('Novak', sa.String(), nullable=False),
    sa.Column('Muz', sa.Boolean(name='zena'), nullable=True),
    sa.Column('datum_insertu', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_loguser'),
    sqlite_autoincrement=True
    )
    op.create_index('ix_loguser_Novak', 'loguser', ['Novak'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_loguser_Novak', table_name='loguser')
    op.drop_table('loguser')
    ### end Alembic commands ###
